### ISSUE TITLE
Fibonacci

### ISSUE THREAD

**Issue by GregLeBarbar** [ETML-INF/php-unit-tests#2]

**Comment by GregLeBarbar** [comment]
#1 PR

**Comment by zfpggz** [comment]
Hello Gregory :-)
Oualà ... je suis parvenu à atteindre ton dépôt pour les PO. 
J'ai cloner le repo sur ma tablette. J'ai installé XAMPP et mis une copie de ton appli dans htdocs.
Là, je ne parviens qu'à faire afficher le message de index.php.
Je ne parviens pas à exécuter ./src/leap.php ni ./tests/leapTest.php 
Est-ce normal, car en cours, ou peux-tu m'aider à solutionner cela ? Pas urgent :-)
Merci et bravo pour ta démarche, et cordiales salutations
Gilbert

**Comment by zfpggz** [comment]
Oups, je n'avais pas fait un checkout sur la branche fibonacci ... . C'est moi qui me suis tromnpé.
Toutefois, lorsque j'exécute le code, j'obtiens cela 👍 
Fatal error: Uncaught Error: Class "PHPUnit\Framework\TestCase" not found in C:\xampp\htdocs\gregory\tests\fibonacciTest.php:7 Stack trace: #0 {main} thrown in C:\xampp\htdocs\gregory\tests\fibonacciTest.php on line 7

Là ... je ne sais pas. Il me manque quelque chose. Dois-je utiliser autre chose que xampp ? Quoi d'autre ?

Merci et bye

GG

**Comment by GregLeBarbar** [comment]
@zfpggz Merci pour tes remarques ! Je pense qu'il faut que tu fasses un `composer install` à la racine du projet pour installer les dépendances et en particulier phpunit.
D'ailleurs j'ai mis à jour le Readme.md en expliquant un peu plus comment faire.
